---
title: "VAST Challenge MC2 - Part 2"
description: |
  This post presents the step by step instructions that were followed to identify which GASTech employess made which purchases and identify suspicious patterns of behavior using visual analytic techniques.
author:
  - name: Mayurapriyann Arulmozhi Baskaran
    url: https://www.linkedin.com/in/mayurapriyann/
date: 07-25-2021
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_float: true
    smooth_scroll: true
    theme: united
    highlight: tango
preview: 1.jpg
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, error=FALSE)
```

```{r}
packages = c('raster','sf','tmap','tidyverse','clock','rgdal','tidytext','widyr',
             'DT','dplyr','hms','ggraph','igraph','crosstalk',
             'plotly','data.table','stringi','mapview','ggridges','networkD3',
             'htmlwidgets')

for(p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p, character.only = T)
}
```

**Loading data**

```{r}
cc <- read_csv(file = 'data/cc_data.csv')
lc <- read_csv(file = 'data/loyalty_data.csv')
bgmap <- raster("data/MC2-tourist.tif")
Abila_st <- st_read(dsn = "data/Geospatial",
                    layer = "Abila")
gps <- read_csv("data/gps.csv")
net <- read_csv(file = 'data/car-assignments.csv')
```


