---
title: "In-class Exercise 8"
description: |
  This post presents the step by step instructions that were followed to achieve the corresponding visualizations in Session 8 of our Visual Analytics Module.
author:
  - name: Mayurapriyann Arulmozhi Baskaran
    url: https://www.linkedin.com/in/mayurapriyann/
date: 07-03-2021
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_float: true
    smooth_scroll: true
    theme: united
    highlight: tango
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, error = FALSE)
```

## Installing and Launching R Packages


```{r }
packages = c('raster','sf','tmap','tidyverse','clock','rgdal')

for(p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p, character.only = T)
}
```


```{r }
ap <- raster("C:/Users/Mayur/Documents/SMU/Sem3/Visual Analytics/Session8/In-class_Ex08/Geospatial/MC2-tourist.tif")
```

# Importing Raster File

```{r }
bgmap <- raster("C:/Users/Mayur/Documents/SMU/Sem3/Visual Analytics/Session8/In-class_Ex08/Geospatial/MC2-tourist.tif")
bgmap
```

# Plotting Raster Layer

```{r }
tmap_mode("plot")
tm_shape(bgmap) +
  tm_raster(bgmap,
            legend.show = FALSE)
```

# Plotting Raster Layer using RGB

```{r }
tm_shape(bgmap) +
tm_rgb(bgmap, r = 1, g = 2, b = 3,
       alpha = NA,
       saturation = 1,
       interpolate = TRUE,
       max.value = 255)
```

# Importing Vector GIS Data File

```{r }
Abila_st <- st_read(dsn = "C:/Users/Mayur/Documents/SMU/Sem3/Visual Analytics/Session8/In-class_Ex08/Geospatial",
                    layer = "Abila")
```

# Importing Aspatial Data

```{r }
gps <- read_csv("C:/Users/Mayur/Documents/SMU/Sem3/Visual Analytics/Session8/In-class_Ex08/aspatial/gps.csv")
glimpse(gps)
```

# Converting Date-Time Field and ID Field

```{r }
gps$Timestamp <- date_time_parse(gps$Timestamp,
                                 zone = "",
                                 format = "%m/%d/%Y %H:%M:%S")
gps$id <- as_factor(gps$id)
```

```{r }
gps1 <- gps %>%
  filter(Timestamp < "2014-01-06 23:59:00")
```

# Converting Aspatial Data Into A Simple Feature data Frame

```{r }
gps_sf <- st_as_sf(gps,
                   coords = c("long","lat"),
                   crs = 4326)
```

# Creating Movement Path From GPS Points

```{r }
gps_path <- gps_sf %>%
  group_by(id) %>%
  summarize(m= mean(Timestamp),
            do_union=FALSE) %>%
  st_cast("LINESTRING")
```

# Plotting the GPS Paths

```{r }
gps_path_selected <- gps_path %>%
  filter(id==1)
tmap_mode("view")
tm_shape(bgmap) +
  tm_rgb(bgmap, r = 1, g = 2, b = 3,
         alpha = NA,
         saturation = 1,
         interpolate = TRUE,
         max.value = 255) +
  tm_shape(gps_path_selected) +
  tm_lines()
```


